spring:
  application:
    name: ceptracker
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  endpoints:
    web:
      exposure:
        include: "*"

  management:
    server:
      port: ${ACTUATOR_PORT:8082}
      endpoint:
        health:
          show-details: always

management:
  datadog:
    metrics:
      export:
        application-key: ${DD_APPLICATION_KEY}
        api-key: ${DD_API_KEY}
        step: 5s
        uri: ${DD_URI}
      web:
        server:
          request:
            autotime:
              enabled: true
    endpoints:
      web:
        exposure:
          include: "*"

  metrics:
    export:
      host: api.datadoghq.com
      step: 5s
      agent-host: localhost

    datadog:
      metrics:
        enabled: true
